### ISSUE TITLE
Can't able to use ng-click, with this ripple directive.. :/

### ISSUE THREAD

**Issue by manushvenkatesh** [exodusanto/ng-ripple#2]
This Plugin would be great if it supports ng-click also..

**Comment by exodusanto** [comment]
Hi @manushvj, ng-ripple is a directive, so all angular directives are compiled.

Here is one [example](http://codepen.io/exodusanto/pen/rjXyag)

**Comment by manushvenkatesh** [comment]
Thank you so much @exodusanto .. My bad.. Issue was from my code.. This works like a charm.. 🥇

**Comment by exodusanto** [comment]
You're welcome
