### ISSUE TITLE
ng-click is trigger two times with link balise a

### ISSUE THREAD

**Issue by enzogain** [exodusanto/ng-ripple#3]
`ng-click` is trigger two times with a link balise a...

http://codepen.io/Zagonine/pen/GWRLvj

**Comment by exodusanto** [comment]
Yes, because i wrap <a> element with other div and compile it again, i suggest you to apply ng-click to another element inside ripple directive.

[Example](http://codepen.io/exodusanto/pen/PpogRp)

**Comment by exodusanto** [comment]
Fixed with version [1.0.2](https://github.com/exodusanto/ng-ripple/commit/e88277621159ca925930e3b3efdcd23b3315cf95)
