### ISSUE TITLE
ngclick delay

### ISSUE THREAD

**Issue by urielzen** [exodusanto/ng-ripple#4]
Is there a way to include a delay before the ngclick fires? without having a timeout in the logic of my ngclick function?

This is so in a mobile device the users sees the ripple first, having a visual cue of what button they pressed, and after the ripple finishes then the ngclick fires.

Thanks!

**Comment by exodusanto** [comment]
Hi @urielzen, i can't set a delay to the event in my directive... i think the only solution is the timeout in the ng-click function
